// E0 — Backup das tabelas SEINFRA / SINAPI / ORSE em CSV, fora do banco.
//
// Gera 3 arquivos CSV (um por tabela) na pasta ./backup, com cabeçalho, prontos para
// serem reimportados depois. Restaura com (Postgres 17):
//   COPY public.sinapi_itens FROM 'sinapi_itens_AAAA-MM-DD.csv' WITH (FORMAT csv, HEADER match);
// (a coluna id é GENERATED BY DEFAULT AS IDENTITY — aceita os valores do CSV sem ajuste.)
//
// NÃO altera nada no banco. Só lê.
//
// Como rodar (ver README_E0.md para o passo a passo completo):
//   1) cd gecope/sql/reestruturacao_tabelas
//   2) npm install
//   3) SUPABASE_DB_URL="postgresql://...:...@...:5432/postgres" node E0_backup.mjs

import { createWriteStream, mkdirSync, readFileSync, existsSync } from 'node:fs';
import { pipeline } from 'node:stream/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import pg from 'pg';
import { to as copyTo } from 'pg-copy-streams';

const TABELAS = ['sinapi_itens', 'orse_itens', 'seinfra_itens'];
const here = dirname(fileURLToPath(import.meta.url));

// String de conexão, em ordem de preferência:
//   1) argumento na linha de comando:  node E0_backup.mjs "postgresql://..."
//   2) arquivo db-url.local nesta pasta (uma linha só, com a string)
//   3) variável de ambiente SUPABASE_DB_URL
const urlFile = join(here, 'db-url.local');
let connectionString =
  process.argv[2] ||
  (existsSync(urlFile) ? readFileSync(urlFile, 'utf8').trim() : '') ||
  process.env.SUPABASE_DB_URL;

if (!connectionString) {
  console.error('\nERRO: não achei a string de conexão do banco.');
  console.error('Faça UMA destas opções:');
  console.error('  A) crie o arquivo  db-url.local  nesta pasta e cole a string dentro dele; ou');
  console.error('  B) rode:  node E0_backup.mjs "postgresql://postgres.<ref>:<SENHA>@...pooler.supabase.com:5432/postgres"\n');
  process.exitCode = 1;
  process.exit();
}
if (connectionString.includes('[YOUR-PASSWORD]')) {
  console.error('\nERRO: a string ainda está com [YOUR-PASSWORD]. Troque pela senha real do banco.\n');
  process.exitCode = 1;
  process.exit();
}
// Tira qualquer sslmode=/ssl= da string: o pg v8 novo trata 'require' como 'verify-full' e
// rejeita o certificado próprio do pooler do Supabase. Em vez disso, ligamos TLS pelo
// objeto ssl abaixo (conexão criptografada, sem exigir validação da cadeia de CA).
try {
  const u = new URL(connectionString);
  u.searchParams.delete('sslmode');
  u.searchParams.delete('ssl');
  connectionString = u.toString();
} catch { /* string sem formato URL — segue como veio */ }

const outDir = join(here, 'backup');
mkdirSync(outDir, { recursive: true });

// Data local (não UTC), para o nome do arquivo bater com o dia de quem roda.
const d = new Date();
const stamp = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;

const client = new pg.Client({ connectionString, ssl: { rejectUnauthorized: false } });
await client.connect();
await client.query('SET statement_timeout = 0');
await client.query('SET idle_in_transaction_session_timeout = 0');
console.log('Conectado.\n');

let falhou = false;
for (const tabela of TABELAS) {
  const destino = join(outDir, `${tabela}_${stamp}.csv`);
  try {
    const { rows } = await client.query(`SELECT count(*)::bigint AS n FROM public.${tabela}`);
    const total = BigInt(rows[0].n);

    const src = client.query(
      copyTo(`COPY (SELECT * FROM public.${tabela}) TO STDOUT WITH (FORMAT csv, HEADER true)`)
    );
    await pipeline(src, createWriteStream(destino));

    // Confere: nº de linhas de dados gravadas == count(*). Conta quebras de linha fora
    // de aspas (campos com \n dentro de aspas, como o jsonb, não contam).
    const buf = readFileSync(destino, 'latin1');
    let dataRows = -1; // desconta o cabeçalho
    let inQuotes = false;
    for (let i = 0; i < buf.length; i++) {
      const c = buf[i];
      if (c === '"') inQuotes = !inQuotes;
      else if (c === '\n' && !inQuotes) dataRows++;
    }
    if (buf.length && buf[buf.length - 1] !== '\n' && !inQuotes) dataRows++; // última linha sem \n final

    if (BigInt(dataRows) !== total) {
      falhou = true;
      console.error(`FALHA ${tabela}: gravou ${dataRows} linhas, esperado ${total} — arquivo INCOMPLETO.`);
    } else {
      console.log(`OK  ${tabela}: ${total} linhas -> ${destino}`);
    }
  } catch (err) {
    falhou = true;
    console.error(`FALHA ${tabela}: ${err.message}`);
  }
}

await client.end();
console.log('\nConcluído.' + (falhou ? ' (COM FALHAS — não use este backup, ver acima)' : ''));
if (!falhou) console.log('Guarde a pasta ./backup fora do Supabase (computador / Google Drive).');
process.exitCode = falhou ? 1 : 0;
