-- Migração: Checklist de Documentação Mínima para Aditivo
--
-- Contexto: processos de aditivo estavam voltando por falta de documentos porque
-- analistas às vezes esqueciam de conferir a documentação mínima antes de mandar
-- o processo para AGUAR. APROVAÇÃO. Esta tabela guarda, em histórico (uma linha
-- por finalização), as respostas do checklist preenchido pelo analista, para que
-- o Diretor (role 'gerente') possa conferir dentro de GERENCIAR PROCESSO antes
-- de assinar no Suite.
--
-- Observação sobre `processo_id`: o tipo real da coluna `processos.id` não está
-- declarado em nenhuma migration deste projeto (a tabela `processos` é anterior
-- à pasta sql/). Para não arriscar falha de criação da FK por tipo incompatível
-- (uuid vs bigint vs texto), `processo_id` é guardado como `text` SEM constraint
-- de foreign key, no mesmo espírito de `cronograma_tarefas.processo` (que também
-- guarda a referência como texto solto). Se quiser reforçar integridade referencial
-- depois, confirme o tipo com:
--   select data_type from information_schema.columns
--   where table_name = 'processos' and column_name = 'id';
-- e então rode manualmente (ajustando o tipo se necessário):
--   alter table checklist_documentacao_aditivo
--     alter column processo_id type <TIPO_REAL> using processo_id::<TIPO_REAL>;
--   alter table checklist_documentacao_aditivo
--     add constraint checklist_documentacao_aditivo_processo_id_fkey
--     foreign key (processo_id) references processos(id) on delete cascade;
--
-- Uso: rode este arquivo inteiro no SQL Editor do Supabase (Dashboard > SQL Editor).

begin;

create table if not exists checklist_documentacao_aditivo (
  id                              bigint generated by default as identity primary key,
  processo_id                     text not null,
  processo_nup                    text,
  status_gatilho                  text not null default 'AGUAR. APROVAÇÃO',

  eh_primeiro_aditivo             boolean not null,

  planilha_orcamentaria_validada  boolean not null,
  planilha_orcamentaria_obs       text,
  memoria_calculo                 boolean not null,
  memoria_calculo_obs             text,
  parecer_tecnico                 boolean not null,
  parecer_tecnico_obs             text,

  -- Itens 4-6: obrigatórios somente quando eh_primeiro_aditivo = true (regra aplicada no cliente)
  art_fiscalizacao                boolean,
  art_fiscalizacao_obs            text,
  art_execucao                    boolean,
  art_execucao_obs                text,
  portaria_fiscalizacao           boolean,
  portaria_fiscalizacao_obs       text,

  curva_abc                       boolean not null,
  curva_abc_obs                   text,

  composicao_propria              boolean not null,
  composicao_propria_obs          text,
  -- composicoes_analiticas: obrigatório somente quando composicao_propria = true
  composicoes_analiticas          boolean,
  composicoes_analiticas_obs      text,

  docs_assinados_fiscalizacao     boolean not null,
  docs_assinados_fiscalizacao_obs text,

  outros_obs                      text,

  autor_nome                      text not null,
  autor_email                     text,
  created_at                      timestamptz not null default now()
);

create index if not exists idx_checklist_aditivo_processo_id      on checklist_documentacao_aditivo (processo_id);
create index if not exists idx_checklist_aditivo_processo_created on checklist_documentacao_aditivo (processo_id, created_at desc);

-- ── RLS: leitura para admin/gerente (Diretor), escrita apenas para admin ────
alter table checklist_documentacao_aditivo enable row level security;

create or replace function checklist_aditivo_pode_ler()
returns boolean
language sql
security definer
stable
as $$
  select exists (
    select 1 from app_users u
    where u.email = auth.jwt() ->> 'email'
      and u.role in ('admin', 'gerente')
  );
$$;

create or replace function checklist_aditivo_pode_escrever()
returns boolean
language sql
security definer
stable
as $$
  select exists (
    select 1 from app_users u
    where u.email = auth.jwt() ->> 'email'
      and u.role = 'admin'
  );
$$;

drop policy if exists "checklist_aditivo_select" on checklist_documentacao_aditivo;
create policy "checklist_aditivo_select" on checklist_documentacao_aditivo
  for select
  using (checklist_aditivo_pode_ler());

drop policy if exists "checklist_aditivo_insert" on checklist_documentacao_aditivo;
create policy "checklist_aditivo_insert" on checklist_documentacao_aditivo
  for insert
  with check (checklist_aditivo_pode_escrever());

drop policy if exists "checklist_aditivo_delete" on checklist_documentacao_aditivo;
create policy "checklist_aditivo_delete" on checklist_documentacao_aditivo
  for delete
  using (checklist_aditivo_pode_escrever());

commit;

-- Verificação pós-migração:
-- select * from checklist_documentacao_aditivo order by created_at desc limit 20;
