-- Migração: Curva ABC integrada ao Processo
--
-- Contexto: hoje a Curva ABC de cada processo é montada num arquivo .xlsx local,
-- fora do GECOPE — o analista marca ok/inconsistência e escreve comentários
-- item a item na planilha, e esse trabalho fica preso no computador de quem
-- fez a análise, sem ficar acessível para consulta futura dentro do sistema.
-- Estas tabelas levam essa mesma análise para dentro de GERENCIAR PROCESSO:
-- a cada upload de planilha é criada uma nova "versão" (curva_abc_versoes),
-- com os itens calculados (curva_abc_itens) para o analista marcar item a
-- item. Reenviar uma planilha revisada não apaga a análise anterior — cria
-- uma nova versão, e a antiga fica preservada só-leitura no histórico (mesmo
-- espírito de checklist_documentacao_aditivo).
--
-- Observação sobre `processo_id`: mesma decisão de create_checklist_documentacao_aditivo.sql
-- e create_alerta_retorno_comentarios.sql (guardado como `text` sem FK rígida,
-- pelo mesmo motivo do tipo desconhecido de `processos.id`). Já
-- `curva_abc_itens.versao_id` referencia `curva_abc_versoes.id`, coluna
-- controlada por esta própria migration, então essa FK é real.
--
-- `processo_id` aceita nulo: o botão "Desvincular" da aba Curva ABC remove
-- definitivamente o vínculo de todas as versões daquele processo (zera
-- processo_id em vez de apagar os dados), pra permitir tirar uma Curva ABC
-- vinculada por engano sem perder o que já foi calculado/analisado.
--
-- Uso: rode este arquivo inteiro no SQL Editor do Supabase (Dashboard > SQL Editor).
-- É seguro rodar de novo depois de uma atualização (create/policy usam
-- "if not exists"/"or replace"/"drop ... if exists").

begin;

create table if not exists curva_abc_versoes (
  id             bigint generated by default as identity primary key,
  processo_id    text not null,
  processo_nup   text,
  versao         int not null,

  arquivo_nome   text,
  arquivo_path   text,
  arquivo_url    text,

  coluna_valor   text,
  criterio_a     numeric,
  criterio_b     numeric,
  criterio_c     numeric,
  total_valor    numeric,
  total_itens    int,

  autor_nome     text not null,
  autor_email    text,
  created_at     timestamptz not null default now(),

  unique (processo_id, versao)
);

create index if not exists idx_curva_abc_versoes_processo_id      on curva_abc_versoes (processo_id);
create index if not exists idx_curva_abc_versoes_processo_versao  on curva_abc_versoes (processo_id, versao desc);

-- permite processo_id nulo (versão "desvinculada" — ver comentário no topo do arquivo);
-- tabelas criadas antes desta atualização tinham a coluna como not null.
alter table curva_abc_versoes alter column processo_id drop not null;

create table if not exists curva_abc_itens (
  id               bigint generated by default as identity primary key,
  versao_id        bigint not null references curva_abc_versoes(id) on delete cascade,

  posicao          int,
  conta            text,
  comp             text,
  descricao        text,
  unidade          text,
  quantidade       numeric,
  valor            numeric,
  pct_individual   numeric,
  pct_acumulado    numeric,
  classe           text,

  status_analise   text not null default 'pendente'
                     check (status_analise in ('pendente', 'ok', 'inconsistencia')),
  comentario       text,
  analisado_por    text,
  analisado_em     timestamptz
);

create index if not exists idx_curva_abc_itens_versao_id on curva_abc_itens (versao_id);

-- Detalhamento por bloco do replanilhamento (CONTRATO/QUANTITATIVO/VALORES):
-- além do par quantidade/valor já usado para montar a curva, guarda as 3
-- quantidades (Acresc./Supr./Replan.) e os 3 valores (V. Acresc./V. Supr./
-- V. Replan.) exibidos lado a lado na tabela, pra versão salva reabrir com o
-- mesmo detalhamento que tinha no momento do upload.
alter table curva_abc_itens add column if not exists qtd_base  numeric;
alter table curva_abc_itens add column if not exists acresc    numeric;
alter table curva_abc_itens add column if not exists suprimido numeric;
alter table curva_abc_itens add column if not exists replan    numeric;
alter table curva_abc_itens add column if not exists v_acresc  numeric;
alter table curva_abc_itens add column if not exists v_suprim  numeric;
alter table curva_abc_itens add column if not exists v_replan  numeric;

-- ── RLS: leitura para admin/gerente/fiscal, escrita para admin/gerente ──────
alter table curva_abc_versoes enable row level security;
alter table curva_abc_itens   enable row level security;

create or replace function curva_abc_pode_ler()
returns boolean
language sql
security definer
stable
as $$
  select exists (
    select 1 from app_users u
    where u.email = auth.jwt() ->> 'email'
      and u.role in ('admin', 'gerente', 'fiscal')
  );
$$;

create or replace function curva_abc_pode_escrever()
returns boolean
language sql
security definer
stable
as $$
  select exists (
    select 1 from app_users u
    where u.email = auth.jwt() ->> 'email'
      and u.role in ('admin', 'gerente')
  );
$$;

drop policy if exists "curva_abc_versoes_select" on curva_abc_versoes;
create policy "curva_abc_versoes_select" on curva_abc_versoes
  for select
  using (curva_abc_pode_ler());

drop policy if exists "curva_abc_versoes_insert" on curva_abc_versoes;
create policy "curva_abc_versoes_insert" on curva_abc_versoes
  for insert
  with check (curva_abc_pode_escrever());

drop policy if exists "curva_abc_versoes_delete" on curva_abc_versoes;
create policy "curva_abc_versoes_delete" on curva_abc_versoes
  for delete
  using (curva_abc_pode_escrever());

drop policy if exists "curva_abc_versoes_update" on curva_abc_versoes;
create policy "curva_abc_versoes_update" on curva_abc_versoes
  for update
  using (curva_abc_pode_escrever())
  with check (curva_abc_pode_escrever());

drop policy if exists "curva_abc_itens_select" on curva_abc_itens;
create policy "curva_abc_itens_select" on curva_abc_itens
  for select
  using (curva_abc_pode_ler());

drop policy if exists "curva_abc_itens_insert" on curva_abc_itens;
create policy "curva_abc_itens_insert" on curva_abc_itens
  for insert
  with check (curva_abc_pode_escrever());

drop policy if exists "curva_abc_itens_update" on curva_abc_itens;
create policy "curva_abc_itens_update" on curva_abc_itens
  for update
  using (curva_abc_pode_escrever())
  with check (curva_abc_pode_escrever());

commit;

-- Verificação pós-migração:
-- select v.*, (select count(*) from curva_abc_itens i where i.versao_id = v.id) as qtd_itens
-- from curva_abc_versoes v order by v.created_at desc limit 20;
