-- Migração: Comentários de Justificativa do Alerta de Retorno
--
-- Contexto: o painel "Aprovados" sinaliza com um ícone de exclamação processos
-- APROVADOS cuja sigla no SUITE está em um setor de risco de retorno para
-- diligência (ver isSetorRiscoDiligencia/aplicarAlertaPreDiligencia em main.js).
-- Faltava um jeito de o usuário registrar por que o processo está naquela
-- situação (ex.: "Solicitação de Cronograma"), o ícone virar um check com a
-- explicação, o processo parar de contar no alerta, e outros usuários poderem
-- ver esse comentário. Esta tabela guarda, em histórico (uma linha por
-- comentário), essas justificativas — cada uma atrelada à sigla do SUITE que
-- motivou o alerta naquele momento, para permitir reabrir o alerta
-- automaticamente se a sigla mudar de novo para outro setor de risco.
--
-- Observação sobre `processo_id`: mesma decisão de create_checklist_documentacao_aditivo.sql
-- (guardado como `text` sem FK rígida, pelo mesmo motivo do tipo desconhecido
-- de `processos.id`).
--
-- Uso: rode este arquivo inteiro no SQL Editor do Supabase (Dashboard > SQL Editor).

begin;

create table if not exists alerta_retorno_comentarios (
  id             bigint generated by default as identity primary key,
  processo_id    text not null,
  processo_nup   text,
  sigla          text not null,
  comentario     text not null,
  autor_nome     text not null,
  autor_email    text,
  created_at     timestamptz not null default now()
);

create index if not exists idx_alerta_retorno_processo_id      on alerta_retorno_comentarios (processo_id);
create index if not exists idx_alerta_retorno_processo_created on alerta_retorno_comentarios (processo_id, created_at desc);

-- ── RLS: leitura para admin/gerente/fiscal, escrita para admin/gerente ──────
alter table alerta_retorno_comentarios enable row level security;

create or replace function alerta_retorno_pode_ler()
returns boolean
language sql
security definer
stable
as $$
  select exists (
    select 1 from app_users u
    where u.email = auth.jwt() ->> 'email'
      and u.role in ('admin', 'gerente', 'fiscal')
  );
$$;

create or replace function alerta_retorno_pode_escrever()
returns boolean
language sql
security definer
stable
as $$
  select exists (
    select 1 from app_users u
    where u.email = auth.jwt() ->> 'email'
      and u.role in ('admin', 'gerente')
  );
$$;

drop policy if exists "alerta_retorno_select" on alerta_retorno_comentarios;
create policy "alerta_retorno_select" on alerta_retorno_comentarios
  for select
  using (alerta_retorno_pode_ler());

drop policy if exists "alerta_retorno_insert" on alerta_retorno_comentarios;
create policy "alerta_retorno_insert" on alerta_retorno_comentarios
  for insert
  with check (alerta_retorno_pode_escrever());

commit;

-- Verificação pós-migração:
-- select * from alerta_retorno_comentarios order by created_at desc limit 20;
