-- Script: autorizacoes_especiais.sql
-- Objetivo: Fase 5 (última) do plano de permissões por papel — a tela de
-- "Autorizações Especiais" em Administração: o Admin concede, pra UM usuário
-- específico, uma das 6 permissões abaixo, sem precisar mudar o papel dele.
-- Fica valendo até o Admin revogar (sem expiração automática — decisão do
-- usuário). Fica registrado quem concedeu, pra quem e quando (e quem revogou
-- e quando, se for o caso) — nunca apaga a linha, só marca como revogada.
--
-- As 6 permissões concedíveis (lista fechada, confirmada com o usuário):
--   financeiro                    — acesso ao módulo Financeiro
--   assistente_dados              — acesso ao Assistente de Dados
--   processos_ver_todos           — Fiscal vê todos os processos, não só os vinculados
--   processos_gravar              — Fiscal/Externo grava/edita/exclui em Processos (igual Gerente)
--   composicoes_editar_terceiros  — Fiscal/Externo edita/exclui composições de qualquer pessoa
--   orcamentos_gravar             — Fiscal/Externo cria/versiona/exclui Orçamentos (igual Gerente)
--
-- NOTA: a lista original combinada com o usuário tinha um 7º item ("acesso ao
-- módulo Contratos"), mas isso ficou sem sentido depois que o usuário mudou a
-- regra de Contratos (Fase 2, revisão) pra "todo mundo logado já pode ver" —
-- conceder acesso a algo que já é universal não faz nada, então foi removido
-- da lista concedível. Se no futuro Contratos precisar de um controle mais
-- fino de novo, um 7º item pode voltar aqui.
--
-- Idempotente: função é CREATE OR REPLACE; tabela/policy/trigger têm
-- IF NOT EXISTS / DROP ... IF EXISTS antes.

BEGIN;

CREATE TABLE IF NOT EXISTS public.autorizacoes_especiais (
  id bigint generated by default as identity primary key,
  usuario_email text not null,
  permissao text not null check (permissao in (
    'financeiro',
    'assistente_dados',
    'processos_ver_todos',
    'processos_gravar',
    'composicoes_editar_terceiros',
    'orcamentos_gravar'
  )),
  concedido_por text not null,
  concedido_em timestamptz not null default now(),
  revogado_por text,
  revogado_em timestamptz,
  unique (usuario_email, permissao)
);

COMMENT ON TABLE public.autorizacoes_especiais IS
  'Autorizações extras concedidas por Admin a um usuário específico, sem mudar o papel dele. Uma linha por par (usuario_email, permissao) — revogar não apaga, só marca revogado_em/revogado_por (histórico completo).';

ALTER TABLE public.autorizacoes_especiais ENABLE ROW LEVEL SECURITY;

-- Qualquer usuário autenticado pode ler as PRÓPRIAS autorizações (o front-end
-- precisa disso pra saber o que mostrar/esconder na própria sessão); Admin lê
-- de todo mundo (é quem gerencia a tela).
DROP POLICY IF EXISTS "autorizacoes_select" ON public.autorizacoes_especiais;
CREATE POLICY "autorizacoes_select"
  ON public.autorizacoes_especiais
  FOR SELECT
  TO authenticated
  USING (
    public.meu_papel() = 'admin'
    OR lower(usuario_email) = lower(auth.jwt() ->> 'email')
  );

-- Só Admin concede (insere) ou revoga (atualiza) — ninguém mais grava aqui.
DROP POLICY IF EXISTS "autorizacoes_insert" ON public.autorizacoes_especiais;
CREATE POLICY "autorizacoes_insert"
  ON public.autorizacoes_especiais
  FOR INSERT
  TO authenticated
  WITH CHECK (public.meu_papel() = 'admin');

DROP POLICY IF EXISTS "autorizacoes_update" ON public.autorizacoes_especiais;
CREATE POLICY "autorizacoes_update"
  ON public.autorizacoes_especiais
  FOR UPDATE
  TO authenticated
  USING (public.meu_papel() = 'admin')
  WITH CHECK (public.meu_papel() = 'admin');

-- Sem policy de DELETE: revogar é sempre soft (revogado_em), nunca apaga a
-- linha — histórico completo, como o usuário pediu.

-- Achado do rev-seguranca: a policy de UPDATE acima só confere QUEM pode
-- gravar (Admin), não O QUÊ — um Admin chamando a API direto (fora da tela)
-- conseguiria reescrever concedido_por/usuario_email/permissao de uma linha
-- já existente, falsificando o próprio histórico que esta tabela existe pra
-- garantir. Trigger fecha isso: usuario_email/permissao nunca mudam depois de
-- criada a linha (são a identidade dela); concedido_por/revogado_por nunca
-- vêm do que o cliente mandou, sempre são forçados pro e-mail de quem está
-- autenticado agora — mesmo que a tela já mande o valor certo, o banco deixa
-- de confiar cegamente nisso.
-- Achado do rev-seguranca (recheck) + rev-correcao (recheck): a 1ª versão do
-- trigger só cobria 2 das 4 combinações possíveis de (OLD.revogado_em,
-- NEW.revogado_em) — faltava tratar "continua ativa" (Admin marca de novo uma
-- permissão que já estava concedida, sem saber — a tela não pré-marca
-- checkboxes já ativos) e "continua revogada". A 1ª faltando fazia o upsert
-- cair no ELSE e estourar exceção — e como o upsert manda várias linhas numa
-- única instrução, isso derrubava o lote inteiro, inclusive concessões novas
-- legítimas no mesmo clique. Também: concedido_em (no INSERT) e revogado_em
-- (ao revogar) não eram forçados pro relógio do servidor, então uma chamada
-- direta à API ainda podia forjar essas datas. Agora as 4 combinações são
-- tratadas explicitamente, e concedido_em/revogado_em são sempre now().
CREATE OR REPLACE FUNCTION public.autorizacoes_protege_integridade()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
BEGIN
  IF TG_OP = 'INSERT' THEN
    NEW.concedido_por := lower(auth.jwt() ->> 'email');
    NEW.concedido_em := now();
    NEW.revogado_por := NULL;
    NEW.revogado_em := NULL;
    RETURN NEW;
  END IF;

  -- usuario_email e permissao são a IDENTIDADE da linha (a chave única) —
  -- nunca podem mudar depois de criada.
  IF NEW.usuario_email IS DISTINCT FROM OLD.usuario_email
     OR NEW.permissao IS DISTINCT FROM OLD.permissao THEN
    RAISE EXCEPTION 'Não é permitido mudar usuário ou permissão de uma autorização já existente — revogue e conceda uma nova, se precisar.';
  END IF;

  IF OLD.revogado_em IS NOT NULL AND NEW.revogado_em IS NULL THEN
    -- Reconcedendo depois de uma revogação (upsert): quem concede agora é
    -- sempre quem está autenticado nesta chamada, nunca o valor mandado pelo
    -- cliente — e a data de concessão é a de agora, não a antiga.
    NEW.concedido_por := lower(auth.jwt() ->> 'email');
    NEW.concedido_em := now();
    NEW.revogado_por := NULL;
  ELSIF OLD.revogado_em IS NULL AND NEW.revogado_em IS NOT NULL THEN
    -- Revogando: concedido_por/concedido_em originais não mudam só porque foi
    -- revogado (isso apagaria quem tinha concedido); quem revoga é sempre
    -- quem está autenticado agora, na hora real do servidor (não a que o
    -- cliente mandar).
    NEW.concedido_por := OLD.concedido_por;
    NEW.concedido_em := OLD.concedido_em;
    NEW.revogado_por := lower(auth.jwt() ->> 'email');
    NEW.revogado_em := now();
  ELSE
    -- OLD.revogado_em e NEW.revogado_em são os dois NULL ("continua ativa" —
    -- ex.: Admin marca de novo uma permissão que já estava concedida, sem
    -- transição real) ou os dois preenchidos ("continua revogada") — em
    -- ambos os casos não houve mudança de estado de verdade, então preserva
    -- tudo do OLD em vez de tentar validar o que o cliente mandou.
    NEW.concedido_por := OLD.concedido_por;
    NEW.concedido_em := OLD.concedido_em;
    NEW.revogado_por := OLD.revogado_por;
    NEW.revogado_em := OLD.revogado_em;
  END IF;

  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_autorizacoes_protege_integridade ON public.autorizacoes_especiais;
CREATE TRIGGER trg_autorizacoes_protege_integridade
  BEFORE INSERT OR UPDATE ON public.autorizacoes_especiais
  FOR EACH ROW EXECUTE FUNCTION public.autorizacoes_protege_integridade();

-- ---------------------------------------------------------------------------
-- Função base + uma função por permissão (nome claro no ponto de uso das
-- policies/triggers das fases anteriores, em vez de espalhar
-- "tenho_autorizacao('processos_gravar')" cru em vários arquivos).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.tenho_autorizacao(p_permissao text)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select exists (
    select 1 from public.autorizacoes_especiais a
    where lower(a.usuario_email) = lower(auth.jwt() ->> 'email')
      and a.permissao = p_permissao
      and a.revogado_em is null
  );
$function$;

CREATE OR REPLACE FUNCTION public.pode_ver_todos_processos()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select public.meu_papel() IN ('admin','gerente','externo')
    OR public.tenho_autorizacao('processos_ver_todos');
$function$;

CREATE OR REPLACE FUNCTION public.pode_gravar_processos()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select public.meu_papel() IN ('admin','gerente')
    OR public.tenho_autorizacao('processos_gravar');
$function$;

CREATE OR REPLACE FUNCTION public.pode_editar_composicoes_terceiros()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select public.meu_papel() IN ('admin','gerente')
    OR public.tenho_autorizacao('composicoes_editar_terceiros');
$function$;

CREATE OR REPLACE FUNCTION public.pode_gravar_orcamentos()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select public.meu_papel() IN ('admin','gerente')
    OR public.tenho_autorizacao('orcamentos_gravar');
$function$;

-- ---------------------------------------------------------------------------
-- Atualiza as policies/triggers das Fases 2/4 pra considerar as autorizações
-- extras. Aditivo por cima do que já existe (mesmo nome de policy/função,
-- DROP+CREATE ou CREATE OR REPLACE) — não deveria mudar nada pra quem não tem
-- nenhuma autorização especial concedida (tenho_autorizacao() dá false pra
-- todo mundo até o Admin conceder a primeira).
-- ---------------------------------------------------------------------------

-- PROCESSOS: ver todos (Fiscal com override) + gravar (Fiscal/Externo com override)
DROP POLICY IF EXISTS "processos_select" ON public.processos;
CREATE POLICY "processos_select"
  ON public.processos
  FOR SELECT
  TO authenticated
  USING (
    public.pode_ver_todos_processos()
    OR (
      public.meu_papel() = 'fiscal'
      AND (
        processos.fiscal_matricula = public.minha_matricula()
        OR processos.fiscal_matricula IS NULL
      )
    )
  );

DROP POLICY IF EXISTS "processos_insert" ON public.processos;
CREATE POLICY "processos_insert"
  ON public.processos
  FOR INSERT
  TO authenticated
  WITH CHECK (public.pode_gravar_processos());

DROP POLICY IF EXISTS "processos_update" ON public.processos;
CREATE POLICY "processos_update"
  ON public.processos
  FOR UPDATE
  TO authenticated
  USING (public.pode_gravar_processos())
  WITH CHECK (public.pode_gravar_processos());
-- processos_restringir_prioridade_meta() não muda: prioridade/meta não estão
-- na lista de 6 permissões concedíveis — continuam estritamente admin-only,
-- mesmo com qualquer autorização especial.

-- COMPOSICOES: editar/excluir de terceiros com override
DROP POLICY IF EXISTS "composicoes_delete" ON public.composicoes_biblioteca;
CREATE POLICY "composicoes_delete"
  ON public.composicoes_biblioteca
  FOR DELETE
  TO authenticated
  USING (
    public.pode_editar_composicoes_terceiros()
    OR lower(criador_email) = lower(auth.jwt() ->> 'email')
  );

CREATE OR REPLACE FUNCTION public.composicoes_pode_atualizar()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE
  v_so_comentario boolean;
BEGIN
  IF public.pode_editar_composicoes_terceiros() THEN
    RETURN NEW;
  END IF;

  v_so_comentario := (to_jsonb(NEW) - 'comentarios_revisao' - 'status')
                    = (to_jsonb(OLD) - 'comentarios_revisao' - 'status');

  IF v_so_comentario THEN
    RETURN NEW; -- comentário/decisão/exclusão-de-item: aberto a qualquer papel válido
  END IF;

  IF lower(OLD.criador_email) = lower(auth.jwt() ->> 'email') THEN
    RETURN NEW; -- dono pode enviar nova versão (ou qualquer outra edição)
  END IF;

  RAISE EXCEPTION 'Você só pode editar (nova versão) composições que você mesmo criou.';
END;
$function$;

-- ORCAMENTOS: criar/nova versão/excluir com override
DROP POLICY IF EXISTS "orcamentos_insert" ON public.orcamentos_biblioteca;
CREATE POLICY "orcamentos_insert"
  ON public.orcamentos_biblioteca
  FOR INSERT
  TO authenticated
  WITH CHECK (public.pode_gravar_orcamentos());

DROP POLICY IF EXISTS "orcamentos_delete" ON public.orcamentos_biblioteca;
CREATE POLICY "orcamentos_delete"
  ON public.orcamentos_biblioteca
  FOR DELETE
  TO authenticated
  USING (public.pode_gravar_orcamentos());

CREATE OR REPLACE FUNCTION public.orcamentos_pode_atualizar()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE
  v_so_comentario boolean;
BEGIN
  IF public.pode_gravar_orcamentos() THEN
    RETURN NEW;
  END IF;

  v_so_comentario := (to_jsonb(NEW) - 'comentarios_revisao' - 'status')
                    = (to_jsonb(OLD) - 'comentarios_revisao' - 'status');

  IF v_so_comentario THEN
    RETURN NEW; -- comentário/decisão/exclusão-de-item: aberto a qualquer papel válido
  END IF;

  RAISE EXCEPTION 'Nova versão de orçamento é permitida só para Admin/Gerente (ou quem tem autorização especial).';
END;
$function$;

COMMIT;
